[common-etcd]
host = "127.0.0.1:2379"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
connectionTimeout = 3

[common-redis]
redisAddress = "127.0.0.1:6379"
redisPassword = ""
db = 0